// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::config::RequestConfig;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Attachments API.
#[derive(Debug, Clone)]
pub struct AttachmentsClient<'a> {
    client: &'a TofuPilot,
}

impl<'a> AttachmentsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// Initialize upload
    ///
    /// Get a temporary pre-signed URL to upload a file. Returns the upload ID and URL. Upload the file to the URL with a PUT request, then call Finalize upload.
    pub fn initialize(&self) -> InitializeBuilder<'a> {
        InitializeBuilder::new(self.client)
    }

    /// Delete attachments
    ///
    /// Permanently delete attachments by their IDs and unlink them from any associated runs or units. Removes files from storage and clears all references.
    pub fn delete(&self) -> DeleteBuilder<'a> {
        DeleteBuilder::new(self.client)
    }

    /// Finalize upload
    ///
    /// Finalize a file upload after uploading to the pre-signed URL. Validates the file and records its metadata.
    pub fn finalize(&self) -> FinalizeBuilder<'a> {
        FinalizeBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// InitializeBuilder
// ---------------------------------------------------------------------------

/// Builder for [`AttachmentsClient::initialize`].
///
/// # Example
///
/// ```ignore
/// let response = client.attachments().initialize()
///     .name(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct InitializeBuilder<'a> {
    client: &'a TofuPilot,
    name: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> InitializeBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            name: None,
            request_config: None,
        }
    }

    /// Set the `name` field.
    ///
    /// File name including extension (e.g. "report.pdf")
    pub fn name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: AttachmentInitializeRequest) -> Self {
        self.name = Some(body.name);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<AttachmentInitializeResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/attachments");

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );


        let body = AttachmentInitializeRequest {
            name: self.name
                .ok_or_else(|| Error::Validation(
                    "missing required field: name".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "attachment-initialize",
            self.request_config.as_ref(),
        ).await?;
        let result: AttachmentInitializeResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// DeleteBuilder
// ---------------------------------------------------------------------------

/// Builder for [`AttachmentsClient::delete`].
///
/// # Example
///
/// ```ignore
/// let response = client.attachments().delete()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct DeleteBuilder<'a> {
    client: &'a TofuPilot,
    ids: Option<Vec<String>>,
    request_config: Option<RequestConfig>,
}

impl<'a> DeleteBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            ids: None,
            request_config: None,
        }
    }

    /// Set the `ids` query parameter.
    ///
    /// Upload IDs to delete
    pub fn ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.ids = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<AttachmentDeleteResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/attachments");

        let mut request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );

        if let Some(ref val) = self.ids {
            for item in val {
                request = request.query(&[("ids", item.to_string())]);
            }
        }


        let response = self.client.execute(
            request,
            "attachment-delete",
            self.request_config.as_ref(),
        ).await?;
        let result: AttachmentDeleteResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// FinalizeBuilder
// ---------------------------------------------------------------------------

/// Builder for [`AttachmentsClient::finalize`].
///
/// # Example
///
/// ```ignore
/// let response = client.attachments().finalize()
///     .id(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct FinalizeBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> FinalizeBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            request_config: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// ID of the upload to finalize
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<AttachmentFinalizeResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = urlencoding::encode(&id);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/attachments/{id}/finalize",
            base_url,
            id = id_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );



        let response = self.client.execute(
            request,
            "attachment-finalize",
            self.request_config.as_ref(),
        ).await?;
        let result: AttachmentFinalizeResponse = response.json().await?;
        Ok(result)
    }
}

