// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use std::sync::Arc;
use std::time::Duration;

use reqwest::header::{HeaderValue, AUTHORIZATION, USER_AGENT};

use crate::config::ClientConfig;
use crate::error::{Error, Result};
use crate::hooks::HookContext;
use crate::procedures::ProceduresClient;
use crate::versions::VersionsClient;
use crate::runs::RunsClient;
use crate::attachments::AttachmentsClient;
use crate::units::UnitsClient;
use crate::parts::PartsClient;
use crate::revisions::RevisionsClient;
use crate::batches::BatchesClient;
use crate::stations::StationsClient;
use crate::users::UsersClient;
use crate::imports::ImportsClient;
use crate::logs::LogsClient;
use crate::phases::PhasesClient;
use crate::measurements::MeasurementsClient;
use crate::deployments::DeploymentsClient;

/// TofuPilot API client.
///
/// Provides access to all TofuPilot API resources with typed requests,
/// typed errors, retry logic, and request lifecycle hooks.
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// #[tokio::main]
/// async fn main() -> tofupilot::Result<()> {
///     let client = TofuPilot::new("your-api-key");
///
///     let procedures = client.procedures().list().send().await?;
///     println!("{:?}", procedures);
///     Ok(())
/// }
/// ```
#[derive(Debug, Clone)]
pub struct TofuPilot {
    pub(crate) http: reqwest::Client,
    pub(crate) http_external: reqwest::Client,
    pub(crate) config: ClientConfig,
    /// Auth and telemetry headers, applied to every API request in execute().
    headers: reqwest::header::HeaderMap,
}

impl TofuPilot {
    /// Create a new client with the given API key.
    pub fn new(api_key: impl Into<String>) -> Self {
        Self::with_config(ClientConfig::new(api_key))
    }

    /// Create a new client with full configuration.
    pub fn with_config(config: ClientConfig) -> Self {
        let mut builder = reqwest::Client::builder().timeout(config.timeout);
        for certificate in &config.root_certificates {
            builder = builder.add_root_certificate(certificate.clone());
        }
        let http = builder
            .build()
            .expect("failed to build HTTP client");

        Self::with_client(config, http)
    }

    /// Create a new client from an existing `reqwest::Client`.
    ///
    /// For transport settings the config does not cover, such as client
    /// certificates or a proxy. The supplied client owns its TLS setup:
    /// `config.root_certificates` is not applied to it. Base URL, timeout,
    /// retries, hooks, and authentication still come from the config — auth
    /// and timeout are applied per request, so the client needs no
    /// credentials of its own.
    pub fn with_client(config: ClientConfig, http: reqwest::Client) -> Self {
        // Presigned attachment URLs point at the instance's storage, which
        // sits behind the same CA on self-hosted deployments.
        let mut external = reqwest::Client::builder();
        for certificate in &config.root_certificates {
            external = external.add_root_certificate(certificate.clone());
        }
        let http_external = external
            .build()
            .expect("failed to build external HTTP client");

        let mut headers = reqwest::header::HeaderMap::new();
        let mut auth = HeaderValue::from_str(&format!("Bearer {}", config.api_key))
            .expect("invalid API key");
        auth.set_sensitive(true); // redacted from Debug output
        headers.insert(AUTHORIZATION, auth);
        headers.insert(
            USER_AGENT,
            HeaderValue::from_str(&config.user_agent).unwrap_or_else(|_| {
                HeaderValue::from_static("tofupilot-rust")
            }),
        );
        headers.insert(
            "x-client-type",
            HeaderValue::from_static("rust"),
        );
        headers.insert(
            "x-client-version",
            HeaderValue::from_str(env!("CARGO_PKG_VERSION")).unwrap_or_else(|_| {
                HeaderValue::from_static("unknown")
            }),
        );

        Self { http, http_external, config, headers }
    }

    /// Access the Procedures API.
    pub fn procedures(&self) -> ProceduresClient<'_> {
        ProceduresClient::new(self)
    }

    /// Access the Versions API.
    pub fn versions(&self) -> VersionsClient<'_> {
        VersionsClient::new(self)
    }

    /// Access the Runs API.
    pub fn runs(&self) -> RunsClient<'_> {
        RunsClient::new(self)
    }

    /// Access the Attachments API.
    pub fn attachments(&self) -> AttachmentsClient<'_> {
        AttachmentsClient::new(self)
    }

    /// Access the Units API.
    pub fn units(&self) -> UnitsClient<'_> {
        UnitsClient::new(self)
    }

    /// Access the Parts API.
    pub fn parts(&self) -> PartsClient<'_> {
        PartsClient::new(self)
    }

    /// Access the Revisions API.
    pub fn revisions(&self) -> RevisionsClient<'_> {
        RevisionsClient::new(self)
    }

    /// Access the Batches API.
    pub fn batches(&self) -> BatchesClient<'_> {
        BatchesClient::new(self)
    }

    /// Access the Stations API.
    pub fn stations(&self) -> StationsClient<'_> {
        StationsClient::new(self)
    }

    /// Access the Users API.
    pub fn users(&self) -> UsersClient<'_> {
        UsersClient::new(self)
    }

    /// Access the Imports API.
    pub fn imports(&self) -> ImportsClient<'_> {
        ImportsClient::new(self)
    }

    /// Access the Logs API.
    pub fn logs(&self) -> LogsClient<'_> {
        LogsClient::new(self)
    }

    /// Access the Phases API.
    pub fn phases(&self) -> PhasesClient<'_> {
        PhasesClient::new(self)
    }

    /// Access the Measurements API.
    pub fn measurements(&self) -> MeasurementsClient<'_> {
        MeasurementsClient::new(self)
    }

    /// Access the Deployments API.
    pub fn deployments(&self) -> DeploymentsClient<'_> {
        DeploymentsClient::new(self)
    }

    /// Execute a request with retry logic and hooks.
    pub(crate) async fn execute(
        &self,
        request: reqwest::RequestBuilder,
        operation_id: &str,
        base_url: &str,
    ) -> Result<reqwest::Response> {
        let hook_ctx = HookContext {
            operation_id: Arc::from(operation_id),
            base_url: Arc::from(base_url),
        };

        // Applied here rather than as client defaults so a caller-supplied
        // client still authenticates.
        let request = request.headers(self.headers.clone());

        let mut last_error: Option<Error> = None;

        for attempt in 0..=self.config.max_retries {
            if attempt > 0 {
                let base_ms = 100u64 * 2u64.pow(attempt - 1);
                let jitter = fastrand::f64() * base_ms as f64;
                let delay = Duration::from_millis(base_ms + jitter as u64);
                tokio::time::sleep(delay).await;
            }

            let req = request
                .try_clone()
                .ok_or_else(|| Error::Validation(
                    "request cannot be cloned (streaming body)".to_string(),
                ))?;

            let mut built = req.build()?;

            // config.timeout is a fallback — a per-builder .timeout() set by a
            // resource call takes precedence. Applied on the built request so
            // it also covers caller-supplied clients with no timeout of their
            // own.
            if built.timeout().is_none() {
                *built.timeout_mut() = Some(self.config.timeout);
            }

            // Run before-request hooks
            let built = self.config.hooks.run_before(&hook_ctx, built).await;

            let result = self.http.execute(built).await;

            match result {
                Ok(response) => {
                    let status = response.status().as_u16();
                    if (200..300).contains(&status) {
                        self.config.hooks.run_after_success(&hook_ctx, &response).await;
                        return Ok(response);
                    }

                    let body = response.text().await.unwrap_or_default();
                    let err = Error::from_response(status, &body);

                    if err.is_retryable() && attempt < self.config.max_retries {
                        self.config.hooks.run_after_error(&hook_ctx, &err).await;
                        last_error = Some(err);
                        continue;
                    }

                    self.config.hooks.run_after_error(&hook_ctx, &err).await;
                    return Err(err);
                }
                Err(e) => {
                    let err = Error::Http(e);
                    if attempt < self.config.max_retries {
                        self.config.hooks.run_after_error(&hook_ctx, &err).await;
                        last_error = Some(err);
                        continue;
                    }
                    self.config.hooks.run_after_error(&hook_ctx, &err).await;
                    return Err(err);
                }
            }
        }

        Err(last_error.unwrap_or_else(|| Error::UnexpectedStatus {
            status: 0,
            body: "max retries exceeded".to_string(),
        }))
    }
}
