// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use std::sync::Arc;
use std::time::Duration;

use reqwest::header::{HeaderValue, AUTHORIZATION, USER_AGENT};

use crate::config::ClientConfig;
use crate::error::{Error, Result};
use crate::hooks::HookContext;
use crate::procedures::ProceduresClient;
use crate::versions::VersionsClient;
use crate::runs::RunsClient;
use crate::attachments::AttachmentsClient;
use crate::units::UnitsClient;
use crate::parts::PartsClient;
use crate::revisions::RevisionsClient;
use crate::batches::BatchesClient;
use crate::stations::StationsClient;
use crate::users::UsersClient;
use crate::imports::ImportsClient;
use crate::logs::LogsClient;
use crate::phases::PhasesClient;
use crate::measurements::MeasurementsClient;
use crate::deployments::DeploymentsClient;

/// TofuPilot API client.
///
/// Provides access to all TofuPilot API resources with typed requests,
/// typed errors, retry logic, and request lifecycle hooks.
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// #[tokio::main]
/// async fn main() -> tofupilot::Result<()> {
///     let client = TofuPilot::new("your-api-key");
///
///     let procedures = client.procedures().list().send().await?;
///     println!("{:?}", procedures);
///     Ok(())
/// }
/// ```
#[derive(Debug, Clone)]
pub struct TofuPilot {
    pub(crate) http: reqwest::Client,
    pub(crate) http_external: reqwest::Client,
    pub(crate) config: ClientConfig,
    /// Auth and telemetry headers, applied to every API request in execute().
    headers: reqwest::header::HeaderMap,
}

/// Install `ring` as the process-wide rustls provider, once.
///
/// The crate builds reqwest with `rustls-no-provider` so that no crypto
/// backend is forced on the binary embedding this SDK; reqwest then panics
/// when it builds a client with nothing installed. Doing it here means
/// `TofuPilot::new(..)` works with no setup, while an application that has
/// already installed its own provider keeps it — `install_default` only
/// succeeds for the first caller and the error is deliberately ignored.
fn ensure_crypto_provider() {
    use std::sync::OnceLock;
    static INSTALLED: OnceLock<()> = OnceLock::new();
    INSTALLED.get_or_init(|| {
        let _ = rustls::crypto::ring::default_provider().install_default();
    });
}

/// Connect timeout for presigned storage transfers.
///
/// Only the connect phase is bounded. A read-idle timeout would look right but
/// breaks uploads: `upload_to_presigned_url` sends a fully-buffered body, so
/// the client writes for the whole transfer and reads nothing until the
/// response arrives — a large attachment on a slow station link is progressing
/// normally yet produces no read event for minutes. Callers that need an
/// overall budget set one per request.
const EXTERNAL_CONNECT_TIMEOUT: Duration = Duration::from_secs(30);

/// The bundled Mozilla roots plus the machine's certificate store.
///
/// Built explicitly because reqwest 0.13 verifies through
/// `rustls-platform-verifier`, which on Unix trusts the OS store ALONE and
/// fails when it is empty — a slim container without `ca-certificates` would
/// lose every HTTPS call. 0.12 shipped webpki roots as a floor; this restores
/// it. A broken OS store degrades to the bundled roots rather than failing.
///
/// Cached: `load_native_certs` hits the filesystem (and the keychain on
/// macOS), which is far too slow to repeat per client.
fn base_root_store() -> &'static rustls::RootCertStore {
    static BASE: std::sync::OnceLock<rustls::RootCertStore> = std::sync::OnceLock::new();
    BASE.get_or_init(|| {
        let mut roots = rustls::RootCertStore::empty();
        roots.extend(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());

        let native = rustls_native_certs::load_native_certs();
        for error in &native.errors {
            log::warn!("could not read the system certificate store: {error}");
        }
        let (_, ignored) = roots.add_parsable_certificates(native.certs);
        if ignored > 0 {
            log::warn!("skipped {ignored} unparsable certificate(s) in the system store");
        }

        roots
    })
}

/// The cached base store plus whatever the caller configured.
fn root_store(config: &ClientConfig) -> rustls::RootCertStore {
    let mut roots = base_root_store().clone();
    let (_, ignored) = roots.add_parsable_certificates(config.root_certificates.iter().cloned());
    if ignored > 0 {
        log::warn!("skipped {ignored} unusable configured root certificate(s)");
    }
    roots
}

/// The rustls configuration the clients are built from.
fn tls_config(config: &ClientConfig) -> rustls::ClientConfig {
    ensure_crypto_provider();
    rustls::ClientConfig::builder()
        .with_root_certificates(root_store(config))
        .with_no_client_auth()
}

impl TofuPilot {
    /// Create a new client with the given API key.
    pub fn new(api_key: impl Into<String>) -> Self {
        Self::with_config(ClientConfig::new(api_key))
    }

    /// Create a new client with full configuration.
    pub fn with_config(config: ClientConfig) -> Self {
        let http = reqwest::Client::builder()
            .timeout(config.timeout)
            .tls_backend_preconfigured(tls_config(&config))
            .build()
            .expect("failed to build HTTP client");

        Self::with_client(config, http)
    }

    /// Create a new client from an existing `reqwest::Client`.
    ///
    /// For transport settings the config does not cover, such as client
    /// certificates or a proxy. The supplied client owns its TLS setup, so a
    /// certificate added to the config is NOT applied to it. Base URL,
    /// timeout, retries, hooks, and authentication still come from the config.
    ///
    /// The separate client for presigned attachment URLs is still built here
    /// and does trust the config's certificates — that storage host sits
    /// behind the same CA on self-hosted deployments. A caller whose own
    /// client carries trust the config lacks must add it to the config too, or
    /// attachment transfers fail while API calls succeed.
    pub fn with_client(config: ClientConfig, http: reqwest::Client) -> Self {
        // Presigned storage transfers are not given `config.timeout`: that is an
        // overall budget suited to API calls, and it would cut large attachment
        // transfers mid-flight. A connect timeout still fails a dead endpoint
        // rather than hanging on the handshake forever.
        let http_external = reqwest::Client::builder()
            .connect_timeout(EXTERNAL_CONNECT_TIMEOUT)
            .tls_backend_preconfigured(tls_config(&config))
            .build()
            .expect("failed to build external HTTP client");

        let mut headers = reqwest::header::HeaderMap::new();
        let mut auth = HeaderValue::from_str(&format!("Bearer {}", config.api_key))
            .expect("invalid API key");
        auth.set_sensitive(true); // redacted from Debug output
        headers.insert(AUTHORIZATION, auth);
        headers.insert(
            USER_AGENT,
            HeaderValue::from_str(&config.user_agent).unwrap_or_else(|_| {
                HeaderValue::from_static("tofupilot-rust")
            }),
        );
        headers.insert(
            "x-client-type",
            HeaderValue::from_static("rust"),
        );
        headers.insert(
            "x-client-version",
            HeaderValue::from_str(env!("CARGO_PKG_VERSION")).unwrap_or_else(|_| {
                HeaderValue::from_static("unknown")
            }),
        );

        Self { http, http_external, config, headers }
    }

    /// Access the Procedures API.
    pub fn procedures(&self) -> ProceduresClient<'_> {
        ProceduresClient::new(self)
    }

    /// Access the Versions API.
    pub fn versions(&self) -> VersionsClient<'_> {
        VersionsClient::new(self)
    }

    /// Access the Runs API.
    pub fn runs(&self) -> RunsClient<'_> {
        RunsClient::new(self)
    }

    /// Access the Attachments API.
    pub fn attachments(&self) -> AttachmentsClient<'_> {
        AttachmentsClient::new(self)
    }

    /// Access the Units API.
    pub fn units(&self) -> UnitsClient<'_> {
        UnitsClient::new(self)
    }

    /// Access the Parts API.
    pub fn parts(&self) -> PartsClient<'_> {
        PartsClient::new(self)
    }

    /// Access the Revisions API.
    pub fn revisions(&self) -> RevisionsClient<'_> {
        RevisionsClient::new(self)
    }

    /// Access the Batches API.
    pub fn batches(&self) -> BatchesClient<'_> {
        BatchesClient::new(self)
    }

    /// Access the Stations API.
    pub fn stations(&self) -> StationsClient<'_> {
        StationsClient::new(self)
    }

    /// Access the Users API.
    pub fn users(&self) -> UsersClient<'_> {
        UsersClient::new(self)
    }

    /// Access the Imports API.
    pub fn imports(&self) -> ImportsClient<'_> {
        ImportsClient::new(self)
    }

    /// Access the Logs API.
    pub fn logs(&self) -> LogsClient<'_> {
        LogsClient::new(self)
    }

    /// Access the Phases API.
    pub fn phases(&self) -> PhasesClient<'_> {
        PhasesClient::new(self)
    }

    /// Access the Measurements API.
    pub fn measurements(&self) -> MeasurementsClient<'_> {
        MeasurementsClient::new(self)
    }

    /// Access the Deployments API.
    pub fn deployments(&self) -> DeploymentsClient<'_> {
        DeploymentsClient::new(self)
    }

    /// Execute a request with retry logic and hooks.
    pub(crate) async fn execute(
        &self,
        request: reqwest::RequestBuilder,
        operation_id: &str,
        base_url: &str,
    ) -> Result<reqwest::Response> {
        let hook_ctx = HookContext {
            operation_id: Arc::from(operation_id),
            base_url: Arc::from(base_url),
        };

        // Applied here rather than as client defaults so a caller-supplied
        // client still authenticates.
        let request = request.headers(self.headers.clone());

        let mut last_error: Option<Error> = None;

        for attempt in 0..=self.config.max_retries {
            if attempt > 0 {
                let base_ms = 100u64 * 2u64.pow(attempt - 1);
                let jitter = fastrand::f64() * base_ms as f64;
                let delay = Duration::from_millis(base_ms + jitter as u64);
                tokio::time::sleep(delay).await;
            }

            let req = request
                .try_clone()
                .ok_or_else(|| Error::Validation(
                    "request cannot be cloned (streaming body)".to_string(),
                ))?;

            let mut built = req.build()?;

            // config.timeout is a fallback — a per-builder .timeout() set by a
            // resource call takes precedence. Applied on the built request so
            // it also covers caller-supplied clients with no timeout of their
            // own.
            if built.timeout().is_none() {
                *built.timeout_mut() = Some(self.config.timeout);
            }

            // Run before-request hooks
            let built = self.config.hooks.run_before(&hook_ctx, built).await;

            let result = self.http.execute(built).await;

            match result {
                Ok(response) => {
                    let status = response.status().as_u16();
                    if (200..300).contains(&status) {
                        self.config.hooks.run_after_success(&hook_ctx, &response).await;
                        return Ok(response);
                    }

                    let body = response.text().await.unwrap_or_default();
                    let err = Error::from_response(status, &body);

                    if err.is_retryable() && attempt < self.config.max_retries {
                        self.config.hooks.run_after_error(&hook_ctx, &err).await;
                        last_error = Some(err);
                        continue;
                    }

                    self.config.hooks.run_after_error(&hook_ctx, &err).await;
                    return Err(err);
                }
                Err(e) => {
                    let err = Error::Http(e);
                    if attempt < self.config.max_retries {
                        self.config.hooks.run_after_error(&hook_ctx, &err).await;
                        last_error = Some(err);
                        continue;
                    }
                    self.config.hooks.run_after_error(&hook_ctx, &err).await;
                    return Err(err);
                }
            }
        }

        Err(last_error.unwrap_or_else(|| Error::UnexpectedStatus {
            status: 0,
            body: "max retries exceeded".to_string(),
        }))
    }
}

#[cfg(test)]
mod trust_floor_tests {
    use super::*;

    /// The bundled Mozilla roots are the floor `root_store` must keep when the
    /// OS store is empty — the slim-container regression this design exists to
    /// prevent. reqwest 0.13's own verifier hard-fails there instead.
    #[test]
    fn bundled_roots_survive_an_empty_system_store() {
        let bundled: std::collections::BTreeSet<_> = webpki_roots::TLS_SERVER_ROOTS
            .iter()
            .map(|anchor| anchor.subject.as_ref().to_vec())
            .collect();
        let store: std::collections::BTreeSet<_> = root_store(&ClientConfig::new("test"))
            .roots
            .iter()
            .map(|anchor| anchor.subject.as_ref().to_vec())
            .collect();

        // Compared by subject, not by count: on a developer machine the OS
        // store alone is large enough to satisfy a length check even with the
        // bundled roots dropped entirely.
        let missing = bundled.difference(&store).count();
        assert_eq!(
            missing, 0,
            "{missing} of the {} bundled Mozilla roots are absent from the store \
             — the built-in floor was lost",
            bundled.len()
        );
    }

    /// Every certificate in a bundle must reach the store, not only the first.
    #[test]
    fn configured_certificates_reach_the_store() {
        let base = root_store(&ClientConfig::new("test")).len();

        let one = rcgen::generate_simple_self_signed(vec!["a.example".to_string()])
            .expect("generate cert")
            .cert
            .pem();
        let two = rcgen::generate_simple_self_signed(vec!["b.example".to_string()])
            .expect("generate cert")
            .cert
            .pem();

        let config = ClientConfig::new("test")
            .add_root_certificate(format!("{one}{two}").as_bytes())
            .expect("parse bundle");

        assert_eq!(
            root_store(&config).len(),
            base + 2,
            "both certificates in the bundle should have been added"
        );
    }
}
