// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::error::{Error, Result};
use percent_encoding::{utf8_percent_encode, AsciiSet, NON_ALPHANUMERIC};

/// Percent-encode set matching RFC 3986 unreserved characters.
const URI_COMPONENT: &AsciiSet = &NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'.')
    .remove(b'_')
    .remove(b'~');
use crate::types::*;

/// Client for the Deployments API.
#[derive(Debug, Clone)]
pub struct DeploymentsClient<'a> {
    pub(crate) client: &'a TofuPilot,
}

impl<'a> DeploymentsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// List and filter deployments
    ///
    /// List deployments with filtering by procedure, environment, build status, branch, author, and date range. Cursor-paginated.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

    /// Get deployment
    ///
    /// Get a deployment by ID, with its artifact metadata, commit, creator, and per-station push state.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`DeploymentsClient::list`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.deployments().list()
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilot,
    procedure_ids: Option<Vec<String>>,
    environments: Option<Vec<Environment>>,
    build_statuses: Option<Vec<DeploymentGetStatus>>,
    pushed: Option<bool>,
    branch_names: Option<Vec<String>>,
    author_usernames: Option<Vec<String>>,
    deployed_after: Option<chrono::DateTime<chrono::Utc>>,
    deployed_before: Option<chrono::DateTime<chrono::Utc>>,
    search_query: Option<String>,
    limit: Option<i64>,
    cursor: Option<i64>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            procedure_ids: None,
            environments: None,
            build_statuses: None,
            pushed: None,
            branch_names: None,
            author_usernames: None,
            deployed_after: None,
            deployed_before: None,
            search_query: None,
            limit: None,
            cursor: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `procedure_ids` query parameter.
    pub fn procedure_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.procedure_ids = Some(value.into());
        self
    }

    /// Set the `environments` query parameter.
    pub fn environments(mut self, value: impl Into<Vec<Environment>>) -> Self {
        self.environments = Some(value.into());
        self
    }

    /// Set the `build_statuses` query parameter.
    pub fn build_statuses(mut self, value: impl Into<Vec<DeploymentGetStatus>>) -> Self {
        self.build_statuses = Some(value.into());
        self
    }

    /// Set the `pushed` query parameter.
    pub fn pushed(mut self, value: impl Into<bool>) -> Self {
        self.pushed = Some(value.into());
        self
    }

    /// Set the `branch_names` query parameter.
    pub fn branch_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.branch_names = Some(value.into());
        self
    }

    /// Set the `author_usernames` query parameter.
    pub fn author_usernames(mut self, value: impl Into<Vec<String>>) -> Self {
        self.author_usernames = Some(value.into());
        self
    }

    /// Set the `deployed_after` query parameter.
    pub fn deployed_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.deployed_after = Some(value.into());
        self
    }

    /// Set the `deployed_before` query parameter.
    pub fn deployed_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.deployed_before = Some(value.into());
        self
    }

    /// Set the `search_query` query parameter.
    pub fn search_query(mut self, value: impl Into<String>) -> Self {
        self.search_query = Some(value.into());
        self
    }

    /// Set the `limit` query parameter.
    ///
    /// Maximum number of deployments to return.
    pub fn limit(mut self, value: impl Into<i64>) -> Self {
        self.limit = Some(value.into());
        self
    }

    /// Set the `cursor` query parameter.
    ///
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    pub fn cursor(mut self, value: impl Into<i64>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<DeploymentListResponse> {

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/deployments");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }

        if let Some(ref val) = self.procedure_ids {
            for item in val {
                request = request.query(&[("procedure_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.environments {
            for item in val {
                request = request.query(&[("environments", item.to_string())]);
            }
        }
        if let Some(ref val) = self.build_statuses {
            for item in val {
                request = request.query(&[("build_statuses", item.to_string())]);
            }
        }
        if let Some(ref val) = self.pushed {
            request = request.query(&[("pushed", val.to_string())]);
        }
        if let Some(ref val) = self.branch_names {
            for item in val {
                request = request.query(&[("branch_names", item.to_string())]);
            }
        }
        if let Some(ref val) = self.author_usernames {
            for item in val {
                request = request.query(&[("author_usernames", item.to_string())]);
            }
        }
        if let Some(ref val) = self.deployed_after {
            request = request.query(&[("deployed_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.deployed_before {
            request = request.query(&[("deployed_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.search_query {
            request = request.query(&[("search_query", val.to_string())]);
        }
        if let Some(ref val) = self.limit {
            request = request.query(&[("limit", val.to_string())]);
        }
        if let Some(ref val) = self.cursor {
            request = request.query(&[("cursor", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "deployment-list",
            base_url,
        ).await?;
        let result: DeploymentListResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`DeploymentsClient::get`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.deployments().get()
///     .id("value")
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// The deployment ID to retrieve.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<DeploymentGetResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = utf8_percent_encode(&id, URI_COMPONENT).to_string();

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/deployments/{id}",
            base_url,
            id = id_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }



        let response = self.client.execute(
            request,
            "deployment-get",
            base_url,
        ).await?;
        let result: DeploymentGetResponse = response.json().await?;
        Ok(result)
    }
}

