// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Imports API.
#[derive(Debug, Clone)]
pub struct ImportsClient<'a> {
    pub(crate) client: &'a TofuPilot,
}

impl<'a> ImportsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// Import runs from files
    ///
    /// Import one or more previously uploaded files (OpenHTF, WATS WSJF/WSXF, ATML, NI TestStand, STDF, or ATDF) in a single call. Each file is parsed independently and its result returned per-item, so one bad file does not fail the others. A file that contains several units (a multi-part STDF/ATDF datalog or a multi-report WSXF/TestStand document) creates one run per unit; all run ids are returned in the item’s `ids`.
    pub fn create_from_files(&self) -> CreateFromFilesBuilder<'a> {
        CreateFromFilesBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// CreateFromFilesBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ImportsClient::create_from_files`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.imports().create_from_files()
///     .items("value")
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct CreateFromFilesBuilder<'a> {
    client: &'a TofuPilot,
    items: Option<Vec<ImportCreateFromFilesItems>>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> CreateFromFilesBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            items: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `items` field.
    ///
    /// Files to import (1–100). Pass a single-item list to import one file. Each item is parsed independently; one failure does not abort the others.
    pub fn items(mut self, value: impl Into<Vec<ImportCreateFromFilesItems>>) -> Self {
        self.items = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: ImportCreateFromFilesRequest) -> Self {
        self.items = Some(body.items);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ImportCreateFromFilesResponse> {

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/import");

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }


        let body = ImportCreateFromFilesRequest {
            items: self.items.unwrap_or_default(),
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "import-createFromFiles",
            base_url,
        ).await?;
        let result: ImportCreateFromFilesResponse = response.json().await?;
        Ok(result)
    }
}

