// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::error::{Error, Result};
use percent_encoding::{utf8_percent_encode, AsciiSet, NON_ALPHANUMERIC};

/// Percent-encode set matching RFC 3986 unreserved characters.
const URI_COMPONENT: &AsciiSet = &NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'.')
    .remove(b'_')
    .remove(b'~');
use crate::types::*;

/// Client for the Logs API.
#[derive(Debug, Clone)]
pub struct LogsClient<'a> {
    pub(crate) client: &'a TofuPilot,
}

impl<'a> LogsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// List and filter logs
    ///
    /// List logs with filtering by run, procedure, level, date range, unit, and source. Cursor-paginated.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

    /// Get log
    ///
    /// Get a single log entry by ID, with its run and unit context.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`LogsClient::list`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.logs().list()
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilot,
    procedure_ids: Option<Vec<String>>,
    search_query: Option<String>,
    levels: Option<Vec<Level>>,
    timestamp_after: Option<chrono::DateTime<chrono::Utc>>,
    timestamp_before: Option<chrono::DateTime<chrono::Utc>>,
    source_files: Option<Vec<String>>,
    run_ids: Option<Vec<String>>,
    run_outcomes: Option<Vec<LogGetOutcome>>,
    procedure_versions: Option<Vec<String>>,
    deployment_ids: Option<Vec<String>>,
    environments: Option<Vec<Environment>>,
    serial_numbers: Option<Vec<String>>,
    part_numbers: Option<Vec<String>>,
    revision_numbers: Option<Vec<String>>,
    batch_numbers: Option<Vec<String>>,
    samples: Option<Vec<Sample>>,
    created_by_station_ids: Option<Vec<String>>,
    created_by_user_ids: Option<Vec<String>>,
    sort_by: Option<LogListSortBy>,
    sort_order: Option<ListSortOrder>,
    limit: Option<i64>,
    cursor: Option<i64>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            procedure_ids: None,
            search_query: None,
            levels: None,
            timestamp_after: None,
            timestamp_before: None,
            source_files: None,
            run_ids: None,
            run_outcomes: None,
            procedure_versions: None,
            deployment_ids: None,
            environments: None,
            serial_numbers: None,
            part_numbers: None,
            revision_numbers: None,
            batch_numbers: None,
            samples: None,
            created_by_station_ids: None,
            created_by_user_ids: None,
            sort_by: None,
            sort_order: None,
            limit: None,
            cursor: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `procedure_ids` query parameter.
    pub fn procedure_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.procedure_ids = Some(value.into());
        self
    }

    /// Set the `search_query` query parameter.
    pub fn search_query(mut self, value: impl Into<String>) -> Self {
        self.search_query = Some(value.into());
        self
    }

    /// Set the `levels` query parameter.
    pub fn levels(mut self, value: impl Into<Vec<Level>>) -> Self {
        self.levels = Some(value.into());
        self
    }

    /// Set the `timestamp_after` query parameter.
    ///
    /// Filter logs with timestamp after this date (inclusive).
    pub fn timestamp_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.timestamp_after = Some(value.into());
        self
    }

    /// Set the `timestamp_before` query parameter.
    ///
    /// Filter logs with timestamp before this date (inclusive).
    pub fn timestamp_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.timestamp_before = Some(value.into());
        self
    }

    /// Set the `source_files` query parameter.
    pub fn source_files(mut self, value: impl Into<Vec<String>>) -> Self {
        self.source_files = Some(value.into());
        self
    }

    /// Set the `run_ids` query parameter.
    pub fn run_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.run_ids = Some(value.into());
        self
    }

    /// Set the `run_outcomes` query parameter.
    pub fn run_outcomes(mut self, value: impl Into<Vec<LogGetOutcome>>) -> Self {
        self.run_outcomes = Some(value.into());
        self
    }

    /// Set the `procedure_versions` query parameter.
    pub fn procedure_versions(mut self, value: impl Into<Vec<String>>) -> Self {
        self.procedure_versions = Some(value.into());
        self
    }

    /// Set the `deployment_ids` query parameter.
    pub fn deployment_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.deployment_ids = Some(value.into());
        self
    }

    /// Set the `environments` query parameter.
    pub fn environments(mut self, value: impl Into<Vec<Environment>>) -> Self {
        self.environments = Some(value.into());
        self
    }

    /// Set the `serial_numbers` query parameter.
    pub fn serial_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.serial_numbers = Some(value.into());
        self
    }

    /// Set the `part_numbers` query parameter.
    pub fn part_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.part_numbers = Some(value.into());
        self
    }

    /// Set the `revision_numbers` query parameter.
    pub fn revision_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.revision_numbers = Some(value.into());
        self
    }

    /// Set the `batch_numbers` query parameter.
    pub fn batch_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.batch_numbers = Some(value.into());
        self
    }

    /// Set the `samples` query parameter.
    pub fn samples(mut self, value: impl Into<Vec<Sample>>) -> Self {
        self.samples = Some(value.into());
        self
    }

    /// Set the `created_by_station_ids` query parameter.
    pub fn created_by_station_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_station_ids = Some(value.into());
        self
    }

    /// Set the `created_by_user_ids` query parameter.
    pub fn created_by_user_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_user_ids = Some(value.into());
        self
    }

    /// Set the `sort_by` query parameter.
    ///
    /// Field to sort results by.
    pub fn sort_by(mut self, value: impl Into<LogListSortBy>) -> Self {
        self.sort_by = Some(value.into());
        self
    }

    /// Set the `sort_order` query parameter.
    ///
    /// Sort order direction.
    pub fn sort_order(mut self, value: impl Into<ListSortOrder>) -> Self {
        self.sort_order = Some(value.into());
        self
    }

    /// Set the `limit` query parameter.
    ///
    /// Maximum number of logs to return.
    pub fn limit(mut self, value: impl Into<i64>) -> Self {
        self.limit = Some(value.into());
        self
    }

    /// Set the `cursor` query parameter.
    pub fn cursor(mut self, value: impl Into<i64>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<LogListResponse> {

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/logs");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }

        if let Some(ref val) = self.procedure_ids {
            for item in val {
                request = request.query(&[("procedure_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.search_query {
            request = request.query(&[("search_query", val.to_string())]);
        }
        if let Some(ref val) = self.levels {
            for item in val {
                request = request.query(&[("levels", item.to_string())]);
            }
        }
        if let Some(ref val) = self.timestamp_after {
            request = request.query(&[("timestamp_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.timestamp_before {
            request = request.query(&[("timestamp_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.source_files {
            for item in val {
                request = request.query(&[("source_files", item.to_string())]);
            }
        }
        if let Some(ref val) = self.run_ids {
            for item in val {
                request = request.query(&[("run_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.run_outcomes {
            for item in val {
                request = request.query(&[("run_outcomes", item.to_string())]);
            }
        }
        if let Some(ref val) = self.procedure_versions {
            for item in val {
                request = request.query(&[("procedure_versions", item.to_string())]);
            }
        }
        if let Some(ref val) = self.deployment_ids {
            for item in val {
                request = request.query(&[("deployment_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.environments {
            for item in val {
                request = request.query(&[("environments", item.to_string())]);
            }
        }
        if let Some(ref val) = self.serial_numbers {
            for item in val {
                request = request.query(&[("serial_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.part_numbers {
            for item in val {
                request = request.query(&[("part_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.revision_numbers {
            for item in val {
                request = request.query(&[("revision_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.batch_numbers {
            for item in val {
                request = request.query(&[("batch_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.samples {
            for item in val {
                request = request.query(&[("samples", item.to_string())]);
            }
        }
        if let Some(ref val) = self.created_by_station_ids {
            for item in val {
                request = request.query(&[("created_by_station_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.created_by_user_ids {
            for item in val {
                request = request.query(&[("created_by_user_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.sort_by {
            request = request.query(&[("sort_by", val.to_string())]);
        }
        if let Some(ref val) = self.sort_order {
            request = request.query(&[("sort_order", val.to_string())]);
        }
        if let Some(ref val) = self.limit {
            request = request.query(&[("limit", val.to_string())]);
        }
        if let Some(ref val) = self.cursor {
            request = request.query(&[("cursor", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "log-list",
            base_url,
        ).await?;
        let result: LogListResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`LogsClient::get`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.logs().get()
///     .id("value")
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// Unique identifier for the log entry.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<LogGetResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = utf8_percent_encode(&id, URI_COMPONENT).to_string();

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/logs/{id}",
            base_url,
            id = id_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }



        let response = self.client.execute(
            request,
            "log-get",
            base_url,
        ).await?;
        let result: LogGetResponse = response.json().await?;
        Ok(result)
    }
}

