// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::error::{Error, Result};
use percent_encoding::{utf8_percent_encode, AsciiSet, NON_ALPHANUMERIC};

/// Percent-encode set matching RFC 3986 unreserved characters.
const URI_COMPONENT: &AsciiSet = &NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'.')
    .remove(b'_')
    .remove(b'~');
use crate::types::*;

/// Client for the Measurements API.
#[derive(Debug, Clone)]
pub struct MeasurementsClient<'a> {
    pub(crate) client: &'a TofuPilot,
}

impl<'a> MeasurementsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// List and filter measurements
    ///
    /// List measurements for a procedure with filtering by phase, measurement, value, outcome, date range, unit, and run details. Cursor-paginated.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

    /// Get measurement
    ///
    /// Get a single measurement by ID, with its value, validators, and run context.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`MeasurementsClient::list`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.measurements().list()
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilot,
    procedure_id: Option<String>,
    phase_name: Option<String>,
    measurement_name: Option<String>,
    phase_names: Option<Vec<String>>,
    outcomes: Option<Vec<LogGetOutcome>>,
    ids: Option<Vec<String>>,
    duration_min: Option<String>,
    duration_max: Option<String>,
    deployment_ids: Option<Vec<String>>,
    procedure_versions: Option<Vec<String>>,
    environments: Option<Vec<Environment>>,
    serial_numbers: Option<Vec<String>>,
    part_numbers: Option<Vec<String>>,
    revision_numbers: Option<Vec<String>>,
    batch_numbers: Option<Vec<String>>,
    operated_by_ids: Option<Vec<String>>,
    created_by_station_ids: Option<Vec<String>>,
    created_by_user_ids: Option<Vec<String>>,
    started_after: Option<chrono::DateTime<chrono::Utc>>,
    started_before: Option<chrono::DateTime<chrono::Utc>>,
    exclude_retries: Option<bool>,
    value_min: Option<f64>,
    value_max: Option<f64>,
    value_bool: Option<bool>,
    value_strings: Option<Vec<String>>,
    measurement_outcomes: Option<Vec<Outcome>>,
    measurement_types: Option<Vec<MeasurementType>>,
    sort_by: Option<MeasurementListSortBy>,
    sort_order: Option<ListSortOrder>,
    limit: Option<i64>,
    cursor: Option<i64>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            procedure_id: None,
            phase_name: None,
            measurement_name: None,
            phase_names: None,
            outcomes: None,
            ids: None,
            duration_min: None,
            duration_max: None,
            deployment_ids: None,
            procedure_versions: None,
            environments: None,
            serial_numbers: None,
            part_numbers: None,
            revision_numbers: None,
            batch_numbers: None,
            operated_by_ids: None,
            created_by_station_ids: None,
            created_by_user_ids: None,
            started_after: None,
            started_before: None,
            exclude_retries: None,
            value_min: None,
            value_max: None,
            value_bool: None,
            value_strings: None,
            measurement_outcomes: None,
            measurement_types: None,
            sort_by: None,
            sort_order: None,
            limit: None,
            cursor: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `procedure_id` query parameter.
    ///
    /// Procedure to list measurements for. Required: measurements are scoped to a single procedure.
    pub fn procedure_id(mut self, value: impl Into<String>) -> Self {
        self.procedure_id = Some(value.into());
        self
    }

    /// Set the `phase_name` query parameter.
    pub fn phase_name(mut self, value: impl Into<String>) -> Self {
        self.phase_name = Some(value.into());
        self
    }

    /// Set the `measurement_name` query parameter.
    pub fn measurement_name(mut self, value: impl Into<String>) -> Self {
        self.measurement_name = Some(value.into());
        self
    }

    /// Set the `phase_names` query parameter.
    pub fn phase_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.phase_names = Some(value.into());
        self
    }

    /// Set the `outcomes` query parameter.
    pub fn outcomes(mut self, value: impl Into<Vec<LogGetOutcome>>) -> Self {
        self.outcomes = Some(value.into());
        self
    }

    /// Set the `ids` query parameter.
    pub fn ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.ids = Some(value.into());
        self
    }

    /// Set the `duration_min` query parameter.
    pub fn duration_min(mut self, value: impl Into<String>) -> Self {
        self.duration_min = Some(value.into());
        self
    }

    /// Set the `duration_max` query parameter.
    pub fn duration_max(mut self, value: impl Into<String>) -> Self {
        self.duration_max = Some(value.into());
        self
    }

    /// Set the `deployment_ids` query parameter.
    pub fn deployment_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.deployment_ids = Some(value.into());
        self
    }

    /// Set the `procedure_versions` query parameter.
    pub fn procedure_versions(mut self, value: impl Into<Vec<String>>) -> Self {
        self.procedure_versions = Some(value.into());
        self
    }

    /// Set the `environments` query parameter.
    pub fn environments(mut self, value: impl Into<Vec<Environment>>) -> Self {
        self.environments = Some(value.into());
        self
    }

    /// Set the `serial_numbers` query parameter.
    pub fn serial_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.serial_numbers = Some(value.into());
        self
    }

    /// Set the `part_numbers` query parameter.
    pub fn part_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.part_numbers = Some(value.into());
        self
    }

    /// Set the `revision_numbers` query parameter.
    pub fn revision_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.revision_numbers = Some(value.into());
        self
    }

    /// Set the `batch_numbers` query parameter.
    pub fn batch_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.batch_numbers = Some(value.into());
        self
    }

    /// Set the `operated_by_ids` query parameter.
    pub fn operated_by_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.operated_by_ids = Some(value.into());
        self
    }

    /// Set the `created_by_station_ids` query parameter.
    pub fn created_by_station_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_station_ids = Some(value.into());
        self
    }

    /// Set the `created_by_user_ids` query parameter.
    pub fn created_by_user_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_user_ids = Some(value.into());
        self
    }

    /// Set the `started_after` query parameter.
    pub fn started_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.started_after = Some(value.into());
        self
    }

    /// Set the `started_before` query parameter.
    pub fn started_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.started_before = Some(value.into());
        self
    }

    /// Set the `exclude_retries` query parameter.
    ///
    /// Exclude retried phase attempts, keeping only the final attempt.
    pub fn exclude_retries(mut self, value: impl Into<bool>) -> Self {
        self.exclude_retries = Some(value.into());
        self
    }

    /// Set the `value_min` query parameter.
    pub fn value_min(mut self, value: impl Into<f64>) -> Self {
        self.value_min = Some(value.into());
        self
    }

    /// Set the `value_max` query parameter.
    pub fn value_max(mut self, value: impl Into<f64>) -> Self {
        self.value_max = Some(value.into());
        self
    }

    /// Set the `value_bool` query parameter.
    pub fn value_bool(mut self, value: impl Into<bool>) -> Self {
        self.value_bool = Some(value.into());
        self
    }

    /// Set the `value_strings` query parameter.
    pub fn value_strings(mut self, value: impl Into<Vec<String>>) -> Self {
        self.value_strings = Some(value.into());
        self
    }

    /// Set the `measurement_outcomes` query parameter.
    pub fn measurement_outcomes(mut self, value: impl Into<Vec<Outcome>>) -> Self {
        self.measurement_outcomes = Some(value.into());
        self
    }

    /// Set the `measurement_types` query parameter.
    pub fn measurement_types(mut self, value: impl Into<Vec<MeasurementType>>) -> Self {
        self.measurement_types = Some(value.into());
        self
    }

    /// Set the `sort_by` query parameter.
    ///
    /// Field to sort results by.
    pub fn sort_by(mut self, value: impl Into<MeasurementListSortBy>) -> Self {
        self.sort_by = Some(value.into());
        self
    }

    /// Set the `sort_order` query parameter.
    ///
    /// Sort order direction.
    pub fn sort_order(mut self, value: impl Into<ListSortOrder>) -> Self {
        self.sort_order = Some(value.into());
        self
    }

    /// Set the `limit` query parameter.
    ///
    /// Maximum number of measurements to return.
    pub fn limit(mut self, value: impl Into<i64>) -> Self {
        self.limit = Some(value.into());
        self
    }

    /// Set the `cursor` query parameter.
    ///
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    pub fn cursor(mut self, value: impl Into<i64>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<MeasurementListResponse> {

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/measurements");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }

        if let Some(ref val) = self.procedure_id {
            request = request.query(&[("procedure_id", val.to_string())]);
        }
        if let Some(ref val) = self.phase_name {
            request = request.query(&[("phase_name", val.to_string())]);
        }
        if let Some(ref val) = self.measurement_name {
            request = request.query(&[("measurement_name", val.to_string())]);
        }
        if let Some(ref val) = self.phase_names {
            for item in val {
                request = request.query(&[("phase_names", item.to_string())]);
            }
        }
        if let Some(ref val) = self.outcomes {
            for item in val {
                request = request.query(&[("outcomes", item.to_string())]);
            }
        }
        if let Some(ref val) = self.ids {
            for item in val {
                request = request.query(&[("ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.duration_min {
            request = request.query(&[("duration_min", val.to_string())]);
        }
        if let Some(ref val) = self.duration_max {
            request = request.query(&[("duration_max", val.to_string())]);
        }
        if let Some(ref val) = self.deployment_ids {
            for item in val {
                request = request.query(&[("deployment_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.procedure_versions {
            for item in val {
                request = request.query(&[("procedure_versions", item.to_string())]);
            }
        }
        if let Some(ref val) = self.environments {
            for item in val {
                request = request.query(&[("environments", item.to_string())]);
            }
        }
        if let Some(ref val) = self.serial_numbers {
            for item in val {
                request = request.query(&[("serial_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.part_numbers {
            for item in val {
                request = request.query(&[("part_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.revision_numbers {
            for item in val {
                request = request.query(&[("revision_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.batch_numbers {
            for item in val {
                request = request.query(&[("batch_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.operated_by_ids {
            for item in val {
                request = request.query(&[("operated_by_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.created_by_station_ids {
            for item in val {
                request = request.query(&[("created_by_station_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.created_by_user_ids {
            for item in val {
                request = request.query(&[("created_by_user_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.started_after {
            request = request.query(&[("started_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.started_before {
            request = request.query(&[("started_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.exclude_retries {
            request = request.query(&[("exclude_retries", val.to_string())]);
        }
        if let Some(ref val) = self.value_min {
            request = request.query(&[("value_min", val.to_string())]);
        }
        if let Some(ref val) = self.value_max {
            request = request.query(&[("value_max", val.to_string())]);
        }
        if let Some(ref val) = self.value_bool {
            request = request.query(&[("value_bool", val.to_string())]);
        }
        if let Some(ref val) = self.value_strings {
            for item in val {
                request = request.query(&[("value_strings", item.to_string())]);
            }
        }
        if let Some(ref val) = self.measurement_outcomes {
            for item in val {
                request = request.query(&[("measurement_outcomes", item.to_string())]);
            }
        }
        if let Some(ref val) = self.measurement_types {
            for item in val {
                request = request.query(&[("measurement_types", item.to_string())]);
            }
        }
        if let Some(ref val) = self.sort_by {
            request = request.query(&[("sort_by", val.to_string())]);
        }
        if let Some(ref val) = self.sort_order {
            request = request.query(&[("sort_order", val.to_string())]);
        }
        if let Some(ref val) = self.limit {
            request = request.query(&[("limit", val.to_string())]);
        }
        if let Some(ref val) = self.cursor {
            request = request.query(&[("cursor", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "measurement-list",
            base_url,
        ).await?;
        let result: MeasurementListResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`MeasurementsClient::get`].
///
/// # Example
///
/// ```no_run
/// use tofupilot::TofuPilot;
///
/// # #[tokio::main]
/// # async fn main() -> tofupilot::Result<()> {
/// let client = TofuPilot::new("your-api-key");
/// let response = client.measurements().get()
///     .id("value")
///     .send()
///     .await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    server_url: Option<String>,
    timeout: Option<std::time::Duration>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            server_url: None,
            timeout: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// ID of the measurement to retrieve.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<MeasurementGetResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = utf8_percent_encode(&id, URI_COMPONENT).to_string();

        let base_url = self.server_url
            .as_deref()
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/measurements/{id}",
            base_url,
            id = id_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(timeout) = self.timeout {
            request = request.timeout(timeout);
        }



        let response = self.client.execute(
            request,
            "measurement-get",
            base_url,
        ).await?;
        let result: MeasurementGetResponse = response.json().await?;
        Ok(result)
    }
}

