// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilot;
use crate::config::RequestConfig;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Procedures API.
#[derive(Debug, Clone)]
pub struct ProceduresClient<'a> {
    client: &'a TofuPilot,
}

impl<'a> ProceduresClient<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self { client }
    }

    /// List and filter procedures
    ///
    /// Retrieve procedures with optional filtering and search. Returns all procedure data including creator, recent runs, and FPY (First Pass Yield) statistics.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

    /// Create procedure
    ///
    /// Create a new test procedure that can be used to organize and track test runs. The procedure serves as a template or framework for organizing test execution.
    pub fn create(&self) -> CreateBuilder<'a> {
        CreateBuilder::new(self.client)
    }

    /// Get procedure
    ///
    /// Retrieve a single procedure by ID, including recent test runs, linked stations, and version history.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

    /// Delete procedure
    ///
    /// Permanently delete a procedure, removing all associated runs, phases, measurements, and attachments.
    pub fn delete(&self) -> DeleteBuilder<'a> {
        DeleteBuilder::new(self.client)
    }

    /// Update procedure
    ///
    /// Update a test procedure's name or configuration. The procedure is identified by its unique ID in the URL path. Only provided fields are modified.
    pub fn update(&self) -> UpdateBuilder<'a> {
        UpdateBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ProceduresClient::list`].
///
/// # Example
///
/// ```ignore
/// let response = client.procedures().list()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilot,
    limit: Option<i64>,
    cursor: Option<f64>,
    search_query: Option<String>,
    created_after: Option<chrono::DateTime<chrono::Utc>>,
    created_before: Option<chrono::DateTime<chrono::Utc>>,
    request_config: Option<RequestConfig>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            limit: None,
            cursor: None,
            search_query: None,
            created_after: None,
            created_before: None,
            request_config: None,
        }
    }

    /// Set the `limit` query parameter.
    ///
    /// Maximum number of procedures to return per page.
    pub fn limit(mut self, value: impl Into<i64>) -> Self {
        self.limit = Some(value.into());
        self
    }

    /// Set the `cursor` query parameter.
    pub fn cursor(mut self, value: impl Into<f64>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Set the `search_query` query parameter.
    pub fn search_query(mut self, value: impl Into<String>) -> Self {
        self.search_query = Some(value.into());
        self
    }

    /// Set the `created_after` query parameter.
    pub fn created_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.created_after = Some(value.into());
        self
    }

    /// Set the `created_before` query parameter.
    pub fn created_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.created_before = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureListResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/procedures");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(ref val) = self.limit {
            request = request.query(&[("limit", val.to_string())]);
        }
        if let Some(ref val) = self.cursor {
            request = request.query(&[("cursor", val.to_string())]);
        }
        if let Some(ref val) = self.search_query {
            request = request.query(&[("search_query", val.to_string())]);
        }
        if let Some(ref val) = self.created_after {
            request = request.query(&[("created_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.created_before {
            request = request.query(&[("created_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }


        let response = self.client.execute(
            request,
            "procedure-list",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureListResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// CreateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ProceduresClient::create`].
///
/// # Example
///
/// ```ignore
/// let response = client.procedures().create()
///     .name(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct CreateBuilder<'a> {
    client: &'a TofuPilot,
    name: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> CreateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            name: None,
            request_config: None,
        }
    }

    /// Set the `name` field.
    ///
    /// Name of the procedure. Must be unique within the organization.
    pub fn name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: ProcedureCreateRequest) -> Self {
        self.name = Some(body.name);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureCreateResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/procedures");

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );


        let body = ProcedureCreateRequest {
            name: self.name
                .ok_or_else(|| Error::Validation(
                    "missing required field: name".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "procedure-create",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureCreateResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ProceduresClient::get`].
///
/// # Example
///
/// ```ignore
/// let response = client.procedures().get()
///     .id(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            request_config: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// Unique identifier of the procedure to retrieve.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureGetResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = urlencoding::encode(&id);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{id}",
            base_url,
            id = id_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );



        let response = self.client.execute(
            request,
            "procedure-get",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureGetResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// DeleteBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ProceduresClient::delete`].
///
/// # Example
///
/// ```ignore
/// let response = client.procedures().delete()
///     .id(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct DeleteBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> DeleteBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            request_config: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// Unique identifier of the procedure to delete.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureDeleteResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = urlencoding::encode(&id);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{id}",
            base_url,
            id = id_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );



        let response = self.client.execute(
            request,
            "procedure-delete",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureDeleteResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// UpdateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`ProceduresClient::update`].
///
/// # Example
///
/// ```ignore
/// let response = client.procedures().update()
///     .name(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct UpdateBuilder<'a> {
    client: &'a TofuPilot,
    id: Option<String>,
    name: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> UpdateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilot) -> Self {
        Self {
            client,
            id: None,
            name: None,
            request_config: None,
        }
    }

    /// Set the `id` path parameter.
    ///
    /// Unique identifier of the procedure to update.
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set the `name` field.
    ///
    /// New name for the procedure.
    pub fn name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: ProcedureUpdateRequestBody) -> Self {
        self.name = Some(body.name);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureUpdateResponse> {
        let id = self.id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: id".to_string(),
            ))?;
        let id_encoded = urlencoding::encode(&id);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{id}",
            base_url,
            id = id_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::PATCH,
            &url,
        );


        let body = ProcedureUpdateRequestBody {
            name: self.name
                .ok_or_else(|| Error::Validation(
                    "missing required field: name".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "procedure-update",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureUpdateResponse = response.json().await?;
        Ok(result)
    }
}

