// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilotClient;
use crate::config::RequestConfig;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Revisions API.
#[derive(Debug, Clone)]
pub struct RevisionsClient<'a> {
    client: &'a TofuPilotClient,
}

impl<'a> RevisionsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self { client }
    }

    /// Get part revision
    ///
    /// Retrieve a single part revision by its part number and revision number, including revision metadata, configuration details, and linked units.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

    /// Delete part revision
    ///
    /// Permanently delete a part revision by its part number and revision number. This action removes the revision and all associated data and cannot be undone.
    pub fn delete(&self) -> DeleteBuilder<'a> {
        DeleteBuilder::new(self.client)
    }

    /// Update part revision
    ///
    /// Update a part revision's number or image. Identifies the revision by part number and revision number in the URL.
    pub fn update(&self) -> UpdateBuilder<'a> {
        UpdateBuilder::new(self.client)
    }

    /// Create part revision
    ///
    /// Create a new part revision for an existing part. Revision numbers are matched case-insensitively (e.g., "REV-A" and "rev-a" are considered the same).
    pub fn create(&self) -> CreateBuilder<'a> {
        CreateBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`RevisionsClient::get`].
///
/// # Example
///
/// ```ignore
/// let response = client.revisions().get()
///     .part_number(value)
///     .revision_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilotClient,
    part_number: Option<String>,
    revision_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            part_number: None,
            revision_number: None,
            request_config: None,
        }
    }

    /// Set the `part_number` path parameter.
    ///
    /// Part number that the revision belongs to.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `revision_number` path parameter.
    ///
    /// Revision number to retrieve.
    pub fn revision_number(mut self, value: impl Into<String>) -> Self {
        self.revision_number = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<PartGetRevisionResponse> {
        let part_number = self.part_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: part_number".to_string(),
            ))?;
        let revision_number = self.revision_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: revision_number".to_string(),
            ))?;
        let part_number_encoded = urlencoding::encode(&part_number);
        let revision_number_encoded = urlencoding::encode(&revision_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/parts/{part_number}/revisions/{revision_number}",
            base_url,
            part_number = part_number_encoded,
            revision_number = revision_number_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );



        let response = self.client.execute(
            request,
            "part-getRevision",
            self.request_config.as_ref(),
        ).await?;
        let result: PartGetRevisionResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// DeleteBuilder
// ---------------------------------------------------------------------------

/// Builder for [`RevisionsClient::delete`].
///
/// # Example
///
/// ```ignore
/// let response = client.revisions().delete()
///     .part_number(value)
///     .revision_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct DeleteBuilder<'a> {
    client: &'a TofuPilotClient,
    part_number: Option<String>,
    revision_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> DeleteBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            part_number: None,
            revision_number: None,
            request_config: None,
        }
    }

    /// Set the `part_number` path parameter.
    ///
    /// Part number that the revision belongs to.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `revision_number` path parameter.
    ///
    /// Revision number to delete.
    pub fn revision_number(mut self, value: impl Into<String>) -> Self {
        self.revision_number = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<PartDeleteRevisionResponse> {
        let part_number = self.part_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: part_number".to_string(),
            ))?;
        let revision_number = self.revision_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: revision_number".to_string(),
            ))?;
        let part_number_encoded = urlencoding::encode(&part_number);
        let revision_number_encoded = urlencoding::encode(&revision_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/parts/{part_number}/revisions/{revision_number}",
            base_url,
            part_number = part_number_encoded,
            revision_number = revision_number_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );



        let response = self.client.execute(
            request,
            "part-deleteRevision",
            self.request_config.as_ref(),
        ).await?;
        let result: PartDeleteRevisionResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// UpdateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`RevisionsClient::update`].
///
/// # Example
///
/// ```ignore
/// let response = client.revisions().update()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct UpdateBuilder<'a> {
    client: &'a TofuPilotClient,
    part_number: Option<String>,
    revision_number: Option<String>,
    number: Option<String>,
    image_id: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> UpdateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            part_number: None,
            revision_number: None,
            number: None,
            image_id: None,
            request_config: None,
        }
    }

    /// Set the `part_number` path parameter.
    ///
    /// Part number that the revision belongs to.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `revision_number` path parameter.
    ///
    /// Current revision number to update.
    pub fn revision_number(mut self, value: impl Into<String>) -> Self {
        self.revision_number = Some(value.into());
        self
    }

    /// Set the `number` field.
    ///
    /// New revision number to set.
    pub fn number(mut self, value: impl Into<String>) -> Self {
        self.number = Some(value.into());
        self
    }

    /// Set the `image_id` field.
    ///
    /// Upload ID for the revision image, or empty string to remove image
    pub fn image_id(mut self, value: impl Into<String>) -> Self {
        self.image_id = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: PartUpdateRevisionRequestBody) -> Self {
        if body.number.is_some() {
            self.number = body.number;
        }
        if body.image_id.is_some() {
            self.image_id = body.image_id;
        }
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<PartUpdateRevisionResponse> {
        let part_number = self.part_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: part_number".to_string(),
            ))?;
        let revision_number = self.revision_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: revision_number".to_string(),
            ))?;
        let part_number_encoded = urlencoding::encode(&part_number);
        let revision_number_encoded = urlencoding::encode(&revision_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/parts/{part_number}/revisions/{revision_number}",
            base_url,
            part_number = part_number_encoded,
            revision_number = revision_number_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::PATCH,
            &url,
        );


        let body = PartUpdateRevisionRequestBody {
            number: self.number,
            image_id: self.image_id,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "part-updateRevision",
            self.request_config.as_ref(),
        ).await?;
        let result: PartUpdateRevisionResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// CreateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`RevisionsClient::create`].
///
/// # Example
///
/// ```ignore
/// let response = client.revisions().create()
///     .number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct CreateBuilder<'a> {
    client: &'a TofuPilotClient,
    part_number: Option<String>,
    number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> CreateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            part_number: None,
            number: None,
            request_config: None,
        }
    }

    /// Set the `part_number` path parameter.
    ///
    /// Part number to create a revision for.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `number` field.
    ///
    /// Revision number (e.g., version number or code).
    pub fn number(mut self, value: impl Into<String>) -> Self {
        self.number = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: PartCreateRevisionRequestBody) -> Self {
        self.number = Some(body.number);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<PartCreateRevisionResponse> {
        let part_number = self.part_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: part_number".to_string(),
            ))?;
        let part_number_encoded = urlencoding::encode(&part_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/parts/{part_number}/revisions",
            base_url,
            part_number = part_number_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );


        let body = PartCreateRevisionRequestBody {
            number: self.number
                .ok_or_else(|| Error::Validation(
                    "missing required field: number".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "part-createRevision",
            self.request_config.as_ref(),
        ).await?;
        let result: PartCreateRevisionResponse = response.json().await?;
        Ok(result)
    }
}

