// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilotClient;
use crate::config::RequestConfig;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Units API.
#[derive(Debug, Clone)]
pub struct UnitsClient<'a> {
    client: &'a TofuPilotClient,
}

impl<'a> UnitsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self { client }
    }

    /// List and filter units
    ///
    /// Retrieve a paginated list of units with filtering by serial number, part number, and batch. Uses cursor-based pagination for efficient large dataset traversal.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

    /// Create unit
    ///
    /// Create a new unit with a serial number and link it to a part revision. Units represent individual hardware items tracked for manufacturing traceability.
    pub fn create(&self) -> CreateBuilder<'a> {
        CreateBuilder::new(self.client)
    }

    /// Delete units
    ///
    /// Permanently delete units by serial number. This action will remove all nested elements and relationships associated with the units.
    pub fn delete(&self) -> DeleteBuilder<'a> {
        DeleteBuilder::new(self.client)
    }

    /// Get unit
    ///
    /// Retrieve a single unit by its serial number. Returns comprehensive unit data including part information, parent/child relationships, and test run history.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

    /// Update unit
    ///
    /// Update unit properties including serial number, part revision, batch assignment, and file attachments with case-insensitive matching.
    pub fn update(&self) -> UpdateBuilder<'a> {
        UpdateBuilder::new(self.client)
    }

    /// Add sub-unit
    ///
    /// Add a sub-unit to a parent unit to track component assemblies and multi-level hardware traceability.
    pub fn add_child(&self) -> AddChildBuilder<'a> {
        AddChildBuilder::new(self.client)
    }

    /// Remove sub-unit
    ///
    /// Remove a sub-unit relationship from a parent unit by serial number. Only unlinks the parent-child relationship; neither unit is deleted from the system.
    pub fn remove_child(&self) -> RemoveChildBuilder<'a> {
        RemoveChildBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::list`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().list()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilotClient,
    search_query: Option<String>,
    ids: Option<Vec<String>>,
    serial_numbers: Option<Vec<String>>,
    part_numbers: Option<Vec<String>>,
    revision_numbers: Option<Vec<String>>,
    batch_numbers: Option<Vec<String>>,
    procedure_ids: Option<Vec<String>>,
    outcomes: Option<Vec<Outcome>>,
    started_after: Option<chrono::DateTime<chrono::Utc>>,
    started_before: Option<chrono::DateTime<chrono::Utc>>,
    latest_only: Option<bool>,
    run_count_min: Option<i64>,
    run_count_max: Option<i64>,
    created_after: Option<chrono::DateTime<chrono::Utc>>,
    created_before: Option<chrono::DateTime<chrono::Utc>>,
    created_by_user_ids: Option<Vec<String>>,
    created_by_station_ids: Option<Vec<String>>,
    exclude_units_with_parent: Option<bool>,
    limit: Option<i64>,
    cursor: Option<i64>,
    sort_by: Option<UnitListSortBy>,
    sort_order: Option<ListSortOrder>,
    request_config: Option<RequestConfig>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            search_query: None,
            ids: None,
            serial_numbers: None,
            part_numbers: None,
            revision_numbers: None,
            batch_numbers: None,
            procedure_ids: None,
            outcomes: None,
            started_after: None,
            started_before: None,
            latest_only: None,
            run_count_min: None,
            run_count_max: None,
            created_after: None,
            created_before: None,
            created_by_user_ids: None,
            created_by_station_ids: None,
            exclude_units_with_parent: None,
            limit: None,
            cursor: None,
            sort_by: None,
            sort_order: None,
            request_config: None,
        }
    }

    /// Set the `search_query` query parameter.
    pub fn search_query(mut self, value: impl Into<String>) -> Self {
        self.search_query = Some(value.into());
        self
    }

    /// Set the `ids` query parameter.
    pub fn ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.ids = Some(value.into());
        self
    }

    /// Set the `serial_numbers` query parameter.
    pub fn serial_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.serial_numbers = Some(value.into());
        self
    }

    /// Set the `part_numbers` query parameter.
    pub fn part_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.part_numbers = Some(value.into());
        self
    }

    /// Set the `revision_numbers` query parameter.
    pub fn revision_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.revision_numbers = Some(value.into());
        self
    }

    /// Set the `batch_numbers` query parameter.
    pub fn batch_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.batch_numbers = Some(value.into());
        self
    }

    /// Set the `procedure_ids` query parameter.
    pub fn procedure_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.procedure_ids = Some(value.into());
        self
    }

    /// Set the `outcomes` query parameter.
    pub fn outcomes(mut self, value: impl Into<Vec<Outcome>>) -> Self {
        self.outcomes = Some(value.into());
        self
    }

    /// Set the `started_after` query parameter.
    pub fn started_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.started_after = Some(value.into());
        self
    }

    /// Set the `started_before` query parameter.
    pub fn started_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.started_before = Some(value.into());
        self
    }

    /// Set the `latest_only` query parameter.
    pub fn latest_only(mut self, value: impl Into<bool>) -> Self {
        self.latest_only = Some(value.into());
        self
    }

    /// Set the `run_count_min` query parameter.
    pub fn run_count_min(mut self, value: impl Into<i64>) -> Self {
        self.run_count_min = Some(value.into());
        self
    }

    /// Set the `run_count_max` query parameter.
    pub fn run_count_max(mut self, value: impl Into<i64>) -> Self {
        self.run_count_max = Some(value.into());
        self
    }

    /// Set the `created_after` query parameter.
    pub fn created_after(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.created_after = Some(value.into());
        self
    }

    /// Set the `created_before` query parameter.
    pub fn created_before(mut self, value: impl Into<chrono::DateTime<chrono::Utc>>) -> Self {
        self.created_before = Some(value.into());
        self
    }

    /// Set the `created_by_user_ids` query parameter.
    pub fn created_by_user_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_user_ids = Some(value.into());
        self
    }

    /// Set the `created_by_station_ids` query parameter.
    pub fn created_by_station_ids(mut self, value: impl Into<Vec<String>>) -> Self {
        self.created_by_station_ids = Some(value.into());
        self
    }

    /// Set the `exclude_units_with_parent` query parameter.
    pub fn exclude_units_with_parent(mut self, value: impl Into<bool>) -> Self {
        self.exclude_units_with_parent = Some(value.into());
        self
    }

    /// Set the `limit` query parameter.
    ///
    /// Maximum number of units to return.
    pub fn limit(mut self, value: impl Into<i64>) -> Self {
        self.limit = Some(value.into());
        self
    }

    /// Set the `cursor` query parameter.
    pub fn cursor(mut self, value: impl Into<i64>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Set the `sort_by` query parameter.
    ///
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    pub fn sort_by(mut self, value: impl Into<UnitListSortBy>) -> Self {
        self.sort_by = Some(value.into());
        self
    }

    /// Set the `sort_order` query parameter.
    ///
    /// Sort order direction.
    pub fn sort_order(mut self, value: impl Into<ListSortOrder>) -> Self {
        self.sort_order = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitListResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/units");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(ref val) = self.search_query {
            request = request.query(&[("search_query", val.to_string())]);
        }
        if let Some(ref val) = self.ids {
            for item in val {
                request = request.query(&[("ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.serial_numbers {
            for item in val {
                request = request.query(&[("serial_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.part_numbers {
            for item in val {
                request = request.query(&[("part_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.revision_numbers {
            for item in val {
                request = request.query(&[("revision_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.batch_numbers {
            for item in val {
                request = request.query(&[("batch_numbers", item.to_string())]);
            }
        }
        if let Some(ref val) = self.procedure_ids {
            for item in val {
                request = request.query(&[("procedure_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.outcomes {
            for item in val {
                request = request.query(&[("outcomes", item.to_string())]);
            }
        }
        if let Some(ref val) = self.started_after {
            request = request.query(&[("started_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.started_before {
            request = request.query(&[("started_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.latest_only {
            request = request.query(&[("latest_only", val.to_string())]);
        }
        if let Some(ref val) = self.run_count_min {
            request = request.query(&[("run_count_min", val.to_string())]);
        }
        if let Some(ref val) = self.run_count_max {
            request = request.query(&[("run_count_max", val.to_string())]);
        }
        if let Some(ref val) = self.created_after {
            request = request.query(&[("created_after", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.created_before {
            request = request.query(&[("created_before", val.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))]);
        }
        if let Some(ref val) = self.created_by_user_ids {
            for item in val {
                request = request.query(&[("created_by_user_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.created_by_station_ids {
            for item in val {
                request = request.query(&[("created_by_station_ids", item.to_string())]);
            }
        }
        if let Some(ref val) = self.exclude_units_with_parent {
            request = request.query(&[("exclude_units_with_parent", val.to_string())]);
        }
        if let Some(ref val) = self.limit {
            request = request.query(&[("limit", val.to_string())]);
        }
        if let Some(ref val) = self.cursor {
            request = request.query(&[("cursor", val.to_string())]);
        }
        if let Some(ref val) = self.sort_by {
            request = request.query(&[("sort_by", val.to_string())]);
        }
        if let Some(ref val) = self.sort_order {
            request = request.query(&[("sort_order", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "unit-list",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitListResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// CreateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::create`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().create()
///     .serial_number(value)
///     .part_number(value)
///     .revision_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct CreateBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_number: Option<String>,
    part_number: Option<String>,
    revision_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> CreateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_number: None,
            part_number: None,
            revision_number: None,
            request_config: None,
        }
    }

    /// Set the `serial_number` field.
    ///
    /// Unique serial number identifier for the unit. Must be unique within the organization.
    pub fn serial_number(mut self, value: impl Into<String>) -> Self {
        self.serial_number = Some(value.into());
        self
    }

    /// Set the `part_number` field.
    ///
    /// Component part number that defines what type of unit this is. If the part does not exist, it will be created.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `revision_number` field.
    ///
    /// Hardware revision identifier for the specific version of the part. If the revision does not exist, it will be created.
    pub fn revision_number(mut self, value: impl Into<String>) -> Self {
        self.revision_number = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: UnitCreateRequest) -> Self {
        self.serial_number = Some(body.serial_number);
        self.part_number = Some(body.part_number);
        self.revision_number = Some(body.revision_number);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitCreateResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/units");

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );


        let body = UnitCreateRequest {
            serial_number: self.serial_number
                .ok_or_else(|| Error::Validation(
                    "missing required field: serial_number".to_string(),
                ))?,
            part_number: self.part_number
                .ok_or_else(|| Error::Validation(
                    "missing required field: part_number".to_string(),
                ))?,
            revision_number: self.revision_number
                .ok_or_else(|| Error::Validation(
                    "missing required field: revision_number".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "unit-create",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitCreateResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// DeleteBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::delete`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().delete()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct DeleteBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_numbers: Option<Vec<String>>,
    request_config: Option<RequestConfig>,
}

impl<'a> DeleteBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_numbers: None,
            request_config: None,
        }
    }

    /// Set the `serial_numbers` query parameter.
    ///
    /// Array of unit serial numbers to delete.
    pub fn serial_numbers(mut self, value: impl Into<Vec<String>>) -> Self {
        self.serial_numbers = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitDeleteResponse> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/units");

        let mut request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );

        if let Some(ref val) = self.serial_numbers {
            for item in val {
                request = request.query(&[("serial_numbers", item.to_string())]);
            }
        }


        let response = self.client.execute(
            request,
            "unit-delete",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitDeleteResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::get`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().get()
///     .serial_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_number: None,
            request_config: None,
        }
    }

    /// Set the `serial_number` path parameter.
    ///
    /// Serial number of the unit to retrieve.
    pub fn serial_number(mut self, value: impl Into<String>) -> Self {
        self.serial_number = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitGetResponse> {
        let serial_number = self.serial_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: serial_number".to_string(),
            ))?;
        let serial_number_encoded = urlencoding::encode(&serial_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/units/{serial_number}",
            base_url,
            serial_number = serial_number_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );



        let response = self.client.execute(
            request,
            "unit-get",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitGetResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// UpdateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::update`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().update()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct UpdateBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_number: Option<String>,
    new_serial_number: Option<String>,
    part_number: Option<String>,
    revision_number: Option<String>,
    batch_number: Option<NullableField<String>>,
    attachments: Option<Vec<String>>,
    request_config: Option<RequestConfig>,
}

impl<'a> UpdateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_number: None,
            new_serial_number: None,
            part_number: None,
            revision_number: None,
            batch_number: None,
            attachments: None,
            request_config: None,
        }
    }

    /// Set the `serial_number` path parameter.
    ///
    /// Serial number of the unit to update.
    pub fn serial_number(mut self, value: impl Into<String>) -> Self {
        self.serial_number = Some(value.into());
        self
    }

    /// Set the `new_serial_number` field.
    ///
    /// New serial number for the unit.
    pub fn new_serial_number(mut self, value: impl Into<String>) -> Self {
        self.new_serial_number = Some(value.into());
        self
    }

    /// Set the `part_number` field.
    ///
    /// New part number for the unit.
    pub fn part_number(mut self, value: impl Into<String>) -> Self {
        self.part_number = Some(value.into());
        self
    }

    /// Set the `revision_number` field.
    ///
    /// New revision number for the unit.
    pub fn revision_number(mut self, value: impl Into<String>) -> Self {
        self.revision_number = Some(value.into());
        self
    }

    /// Set the `batch_number` field.
    ///
    /// New batch number for the unit. Set to null to remove batch.
    pub fn batch_number(mut self, value: impl Into<String>) -> Self {
        self.batch_number = Some(NullableField::Value(value.into()));
        self
    }

    /// Explicitly set `batch_number` to null.
    pub fn batch_number_null(mut self) -> Self {
        self.batch_number = Some(NullableField::Null);
        self
    }

    /// Set the `attachments` field.
    ///
    /// Array of upload IDs to attach to the unit.
    pub fn attachments(mut self, value: impl Into<Vec<String>>) -> Self {
        self.attachments = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: UnitUpdateRequestBody) -> Self {
        if body.new_serial_number.is_some() {
            self.new_serial_number = body.new_serial_number;
        }
        if body.part_number.is_some() {
            self.part_number = body.part_number;
        }
        if body.revision_number.is_some() {
            self.revision_number = body.revision_number;
        }
        self.batch_number = Some(body.batch_number);
        if body.attachments.is_some() {
            self.attachments = body.attachments;
        }
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitUpdateResponse> {
        let serial_number = self.serial_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: serial_number".to_string(),
            ))?;
        let serial_number_encoded = urlencoding::encode(&serial_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/units/{serial_number}",
            base_url,
            serial_number = serial_number_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::PATCH,
            &url,
        );


        let body = UnitUpdateRequestBody {
            new_serial_number: self.new_serial_number,
            part_number: self.part_number,
            revision_number: self.revision_number,
            batch_number: self.batch_number.unwrap_or(NullableField::Absent),
            attachments: self.attachments,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "unit-update",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitUpdateResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// AddChildBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::add_child`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().add_child()
///     .child_serial_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct AddChildBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_number: Option<String>,
    child_serial_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> AddChildBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_number: None,
            child_serial_number: None,
            request_config: None,
        }
    }

    /// Set the `serial_number` path parameter.
    ///
    /// Serial number of the parent unit
    pub fn serial_number(mut self, value: impl Into<String>) -> Self {
        self.serial_number = Some(value.into());
        self
    }

    /// Set the `child_serial_number` field.
    ///
    /// Serial number of the sub-unit to add
    pub fn child_serial_number(mut self, value: impl Into<String>) -> Self {
        self.child_serial_number = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: UnitAddChildRequestBody) -> Self {
        self.child_serial_number = Some(body.child_serial_number);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitAddChildResponse> {
        let serial_number = self.serial_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: serial_number".to_string(),
            ))?;
        let serial_number_encoded = urlencoding::encode(&serial_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/units/{serial_number}/children",
            base_url,
            serial_number = serial_number_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::PUT,
            &url,
        );


        let body = UnitAddChildRequestBody {
            child_serial_number: self.child_serial_number
                .ok_or_else(|| Error::Validation(
                    "missing required field: child_serial_number".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "unit-addChild",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitAddChildResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// RemoveChildBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UnitsClient::remove_child`].
///
/// # Example
///
/// ```ignore
/// let response = client.units().remove_child()
///     .serial_number(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct RemoveChildBuilder<'a> {
    client: &'a TofuPilotClient,
    serial_number: Option<String>,
    child_serial_number: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> RemoveChildBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            serial_number: None,
            child_serial_number: None,
            request_config: None,
        }
    }

    /// Set the `serial_number` path parameter.
    ///
    /// Serial number of the parent unit
    pub fn serial_number(mut self, value: impl Into<String>) -> Self {
        self.serial_number = Some(value.into());
        self
    }

    /// Set the `child_serial_number` query parameter.
    ///
    /// Serial number of the sub-unit to remove
    pub fn child_serial_number(mut self, value: impl Into<String>) -> Self {
        self.child_serial_number = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<UnitRemoveChildResponse> {
        let serial_number = self.serial_number
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: serial_number".to_string(),
            ))?;
        let serial_number_encoded = urlencoding::encode(&serial_number);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/units/{serial_number}/children",
            base_url,
            serial_number = serial_number_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );

        if let Some(ref val) = self.child_serial_number {
            request = request.query(&[("child_serial_number", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "unit-removeChild",
            self.request_config.as_ref(),
        ).await?;
        let result: UnitRemoveChildResponse = response.json().await?;
        Ok(result)
    }
}

