// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilotClient;
use crate::config::RequestConfig;
use crate::error::Result;
use crate::types::*;

/// Client for the User API.
#[derive(Debug, Clone)]
pub struct UserClient<'a> {
    client: &'a TofuPilotClient,
}

impl<'a> UserClient<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self { client }
    }

    /// List users
    ///
    /// Retrieve a list of users in your organization. Use the current parameter to get only the authenticated user profile and permissions.
    pub fn list(&self) -> ListBuilder<'a> {
        ListBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// ListBuilder
// ---------------------------------------------------------------------------

/// Builder for [`UserClient::list`].
///
/// # Example
///
/// ```ignore
/// let response = client.user().list()
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct ListBuilder<'a> {
    client: &'a TofuPilotClient,
    current: Option<bool>,
    request_config: Option<RequestConfig>,
}

impl<'a> ListBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            current: None,
            request_config: None,
        }
    }

    /// Set the `current` query parameter.
    ///
    /// If true, returns only the current authenticated user
    pub fn current(mut self, value: impl Into<bool>) -> Self {
        self.current = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<Vec<UserListResponse>> {

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!("{}{}", base_url, "/v2/users");

        let mut request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );

        if let Some(ref val) = self.current {
            request = request.query(&[("current", val.to_string())]);
        }


        let response = self.client.execute(
            request,
            "user-list",
            self.request_config.as_ref(),
        ).await?;
        let result: Vec<UserListResponse> = response.json().await?;
        Ok(result)
    }
}

