// Code generated by TofuPilot SDK Generator. DO NOT EDIT.

use crate::client::TofuPilotClient;
use crate::config::RequestConfig;
use crate::error::{Error, Result};
use crate::types::*;

/// Client for the Versions API.
#[derive(Debug, Clone)]
pub struct VersionsClient<'a> {
    client: &'a TofuPilotClient,
}

impl<'a> VersionsClient<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self { client }
    }

    /// Get procedure version
    ///
    /// Retrieve a single procedure version by its tag, including version metadata and configuration details.
    pub fn get(&self) -> GetBuilder<'a> {
        GetBuilder::new(self.client)
    }

    /// Delete procedure version
    ///
    /// Permanently delete a procedure version by its tag. This removes the version record and all associated configuration data and cannot be undone.
    pub fn delete(&self) -> DeleteBuilder<'a> {
        DeleteBuilder::new(self.client)
    }

    /// Create procedure version
    ///
    /// Create a new version for an existing test procedure. Versions let you track procedure changes over time and maintain a history of test configurations.
    pub fn create(&self) -> CreateBuilder<'a> {
        CreateBuilder::new(self.client)
    }

}

// ---------------------------------------------------------------------------
// GetBuilder
// ---------------------------------------------------------------------------

/// Builder for [`VersionsClient::get`].
///
/// # Example
///
/// ```ignore
/// let response = client.versions().get()
///     .procedure_id(value)
///     .tag(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct GetBuilder<'a> {
    client: &'a TofuPilotClient,
    procedure_id: Option<String>,
    tag: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> GetBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            procedure_id: None,
            tag: None,
            request_config: None,
        }
    }

    /// Set the `procedure_id` path parameter.
    ///
    /// ID of the procedure that owns this version.
    pub fn procedure_id(mut self, value: impl Into<String>) -> Self {
        self.procedure_id = Some(value.into());
        self
    }

    /// Set the `tag` path parameter.
    ///
    /// Version tag to retrieve.
    pub fn tag(mut self, value: impl Into<String>) -> Self {
        self.tag = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureGetVersionResponse> {
        let procedure_id = self.procedure_id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: procedure_id".to_string(),
            ))?;
        let tag = self.tag
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: tag".to_string(),
            ))?;
        let procedure_id_encoded = urlencoding::encode(&procedure_id);
        let tag_encoded = urlencoding::encode(&tag);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{procedure_id}/versions/{tag}",
            base_url,
            procedure_id = procedure_id_encoded,
            tag = tag_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::GET,
            &url,
        );



        let response = self.client.execute(
            request,
            "procedure-getVersion",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureGetVersionResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// DeleteBuilder
// ---------------------------------------------------------------------------

/// Builder for [`VersionsClient::delete`].
///
/// # Example
///
/// ```ignore
/// let response = client.versions().delete()
///     .procedure_id(value)
///     .tag(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct DeleteBuilder<'a> {
    client: &'a TofuPilotClient,
    procedure_id: Option<String>,
    tag: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> DeleteBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            procedure_id: None,
            tag: None,
            request_config: None,
        }
    }

    /// Set the `procedure_id` path parameter.
    ///
    /// ID of the procedure that owns this version
    pub fn procedure_id(mut self, value: impl Into<String>) -> Self {
        self.procedure_id = Some(value.into());
        self
    }

    /// Set the `tag` path parameter.
    ///
    /// Version tag to delete
    pub fn tag(mut self, value: impl Into<String>) -> Self {
        self.tag = Some(value.into());
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureDeleteVersionResponse> {
        let procedure_id = self.procedure_id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: procedure_id".to_string(),
            ))?;
        let tag = self.tag
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: tag".to_string(),
            ))?;
        let procedure_id_encoded = urlencoding::encode(&procedure_id);
        let tag_encoded = urlencoding::encode(&tag);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{procedure_id}/versions/{tag}",
            base_url,
            procedure_id = procedure_id_encoded,
            tag = tag_encoded,
        );

        let request = self.client.http.request(
            reqwest::Method::DELETE,
            &url,
        );



        let response = self.client.execute(
            request,
            "procedure-deleteVersion",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureDeleteVersionResponse = response.json().await?;
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// CreateBuilder
// ---------------------------------------------------------------------------

/// Builder for [`VersionsClient::create`].
///
/// # Example
///
/// ```ignore
/// let response = client.versions().create()
///     .tag(value)
///     .send()
///     .await?;
/// ```
#[derive(Debug)]
pub struct CreateBuilder<'a> {
    client: &'a TofuPilotClient,
    procedure_id: Option<String>,
    tag: Option<String>,
    request_config: Option<RequestConfig>,
}

impl<'a> CreateBuilder<'a> {
    pub(crate) fn new(client: &'a TofuPilotClient) -> Self {
        Self {
            client,
            procedure_id: None,
            tag: None,
            request_config: None,
        }
    }

    /// Set the `procedure_id` path parameter.
    ///
    /// The ID of the procedure this version belongs to
    pub fn procedure_id(mut self, value: impl Into<String>) -> Self {
        self.procedure_id = Some(value.into());
        self
    }

    /// Set the `tag` field.
    ///
    /// The version tag
    pub fn tag(mut self, value: impl Into<String>) -> Self {
        self.tag = Some(value.into());
        self
    }

    /// Set the full request body (alternative to setting individual fields).
    pub fn body(mut self, body: ProcedureCreateVersionRequestBody) -> Self {
        self.tag = Some(body.tag);
        self
    }

    /// Override the server URL for this request.
    pub fn server_url(mut self, url: impl Into<String>) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .server_url = Some(url.into());
        self
    }

    /// Override the timeout for this request.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.request_config
            .get_or_insert_with(RequestConfig::default)
            .timeout = Some(timeout);
        self
    }

    /// Send the request.
    pub async fn send(self) -> Result<ProcedureCreateVersionResponse> {
        let procedure_id = self.procedure_id
            .ok_or_else(|| Error::Validation(
                "missing required path parameter: procedure_id".to_string(),
            ))?;
        let procedure_id_encoded = urlencoding::encode(&procedure_id);

        let base_url = self.request_config
            .as_ref()
            .and_then(|c| c.server_url.as_deref())
            .unwrap_or(&self.client.config.base_url);

        let url = format!(
            "{}/v2/procedures/{procedure_id}/versions",
            base_url,
            procedure_id = procedure_id_encoded,
        );

        let mut request = self.client.http.request(
            reqwest::Method::POST,
            &url,
        );


        let body = ProcedureCreateVersionRequestBody {
            tag: self.tag
                .ok_or_else(|| Error::Validation(
                    "missing required field: tag".to_string(),
                ))?,
        };
        request = request.json(&body);

        let response = self.client.execute(
            request,
            "procedure-createVersion",
            self.request_config.as_ref(),
        ).await?;
        let result: ProcedureCreateVersionResponse = response.json().await?;
        Ok(result)
    }
}

